#6.	Create k-means clusters for k=4 for the Liver Disorders Data Set at http://archive.ics.uci.edu/ml/datasets/Liver+Disorders . Explain the input parameters you provided for the clustering algorithm. Plot the fitted cluster centers using a different color.  Finally assign the cluster membership for the points to the nearest cluster center.  Color the points according to their cluster membership.	(10+10=20M)

```{r}
setwd("/Users/pemawangmo/Desktop/DS_Notes/DATA_MINING/Final_exam/QUESTION6")
liver_data<-read.csv("Liver_data.csv", header = FALSE, col.names = c("mcv", "alkphos", "sgpt", "sgot", "gammagt", "drinks","selector"))

```
```{r}
library(corrplot)
result = cor(liver_data)
corrplot(result)
```
```{r}
#From the correlation plot it is clear that MCV and gammagt are more dependent on the y variable drinks
#So, for K means these are used as input parameters.

x = liver_data[, c("mcv", "gammagt")]
y = liver_data[, "drinks"]

```

```{r}
plot(x,pch = 19,xlab = expression(x[1]),ylab = expression(x[2]), xlim=c(80,100), ylim=c(0,200))

```
```{r}
plot(x$mcv,y,xlim=c(60,100),ylim=c(0,20),pch=18,col="blue",xlab="mcv",ylab="drinks",main="dependency of mcv on drinks")

```
```{r}
plot(x$gammagt,y,xlim=c(0,100),ylim=c(0,20),pch=19,col="blue",xlab="mcv",ylab="drinks",main="dependency of gammagt on drinks")

```
```{r}
fit = kmeans(x, 4)
plot(x, col=fit$cluster, xlim=c(80,100), ylim=c(0,200))
points(fit$center, col='red', pch=19, cex=2)
```

